name: Deployment Pipeline

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
              with:
               fetch-depth: 0
            - uses: actions/setup-node@v3
              with:
               node-version: 18
            - name: Instalar dependencias
              run: npm install --no-audit --no-fund --no-optional
            - name: Ejecutar los tests
              run: npm test
              